const sidebar = {
    '/base/attribute/': [
        '1.index',
        '1.map',
        '2.map',
        '3.view',
        '4.view',
        '5.layer',
        '6.layer',
        '7.controls',
        '8.controls',
        '9.overlays',
        '10.overlays',
        '11.interactions',
        '12.interactions',
        '13.deploy'
    ],
    '/base/other/': [
        '1.index',
        '1.config',
        '2.skill',
        '3.configureWebpack',
        '4.projectMonitor',
        '5.test',
        '6.configurePrem',
        '7.internationalization',
        '8.errorCollection',
        '9.event',
        '10.server',
        '11.pwa',
        '12.upload',
        '13.video'
    ],
    '/base/vue2.x/': [
        '1.index',
        '1.vue-cli',
        '2.vue',
        '2.vue1',
        '2.vue2',
        '2.vue3',
        '2.vue4',
        '3.vue-router',
        '4.vuex',
        '5.ui',
        '6.utils',
        '7.style',
        '8.eslint',
    ],
    '/base/vue3.x/': [
        '1.index',
        '1.vue-cli3',
        '2.life',
        '2.vue',
        '2.vue1',
        '3.vue-router',
        '4.vuex',
        '5.ui',
        '6.vueuse'
    ],
    '/senior/1.micro/': [
        '1.index',
        '1.singlespa',
        '2.qiankun',
        '3.share'
    ],
    '/senior/2.typescript/': [
        '1.index',
        '1.env',
        '2.base',
        '3.deduction',
        '4.type',
        '5.class',
        '6.interface',
        '7.generic',
        '8.compatible',
        '9.protect',
        '10.infer',
        '11.overlapping',
        '12.condition',
        '13.builtin',
        '14.package',
        '15.custom',
        '16.unknown',
        '17.module',
        '18.statement',
        '19.extend'
    ],
    '/senior/3.deploy/': [
        '1.index',
        '1.local',
        '2.gitlab',
        '3.genkins',
        '4.centos',
        '5.nginx'
    ],
    '/senior/4.component/': [
        '1.index',
        '1.env',
        '1.recursion',
        '2.dynamics',
        '3.dialog',
        '4.render',
        '6.form',
        '7.checkBox',
        '8.dispaly',
        '9.alert',
        '10.renderTable',
        '11.slotScopeTable',
        '12.tree',
        '13.publish',
    ],
    '/source/vue-cli2.x/': [
        '1.index'
    ],
    '/source/vue2.x/': [
        '1.index',
        '2.initGlobalAPI',
        '3.initMixin',
        '4.stateMixin',
        '5.eventsMixin',
        '6.lifecycleMixin',
        '7.renderMixin',
        '8.mount',
        '9.ast',
        '10.optimize',
        '11.gencode',
        '12.mount',
        '13._render',
        '14._update'
    ],
    '/source/vue-router3.x/': [
        '1.index',
        '2.origin'
    ],
}
module.exports = sidebar