const sidebar = {
    '/base/attr/': [
        '1.index',
        '1.map',
        '2.map',
        '3.view',
        '4.view',
        '5.layer',
        '6.layer',
        '7.controls',
        '8.controls',
        '9.overlays',
        '10.overlays',
        '11.interactions',
        '12.interactions',
        '13.deploy'
    ],
    '/base/extend/': [
        '1.index',
        '1.proj',
        '2.feature',
        '3.extent',
        '4.tilegrid',
        '5.format',
        '6.style',
        '7.events',
        '8.render',
        '9.geompoint',
        '10.geomcircle',
        '11.geomlinestring',
        '12.geom',
        '13.data'
    ],
    '/base/source/': [
        '1.index',
        '1.TileArcGISRest',
        '2.BingMaps',
        '3.TileWMS',
        '4.OSM',
        '5.Stamen',
        '6.WMTS',
        '7.XYZ',
        '8.VectorTile',
        '9.GeoTIFF',
        '10.DataTile',
        '11.Vector',
        '12.Heatmap',
        '13.MapboxVector',
        '14.OGCMapTile',
        '15.OGCVectorTile',
        '16.ImageWMS',
        '17.Raster',
        '18.TileJSON',
        '19.GPX',
        '20.WFS',
    ],
    '/base/layer/': [
        '1.index',
        '1.Tile',
        '2.Vector',
        '3.VectorTile',
        '4.ImageStatic'
    ],
    '/senior/vue3.x/': [
        '1.index',
        '1.vue-cli3',
        '2.life',
        '2.vue',
        '2.vue1',
        '3.vue-router',
        '4.vuex',
        '5.ui',
        '6.vueuse'
    ],
    // '/senior/2.typescript/': [
    //     '1.index',
    //     '1.env',
    //     '2.base',
    //     '3.deduction',
    //     '4.type',
    //     '5.class',
    //     '6.interface',
    //     '7.generic',
    //     '8.compatible',
    //     '9.protect',
    //     '10.infer',
    //     '11.overlapping',
    //     '13.builtin',
    //     '14.package',
    //     '15.custom',
    //     '16.unknown',
    //     '17.module',
    //     '18.statement',
    //     '19.extend'
    // ],
    '/senior/3.plugins/': [
        '1.index',
        '1.jsts',
        '2.turf',
        '3.chaikin',
        '4.topojson',
        '5.proj4',
    ],
    '/senior/4.component/': [
        '1.index',
        '1.env',
        '1.recursion',
        '2.dynamics',
        '3.dialog',
        '4.render',
        '6.form',
        '7.checkBox',
        '8.dispaly',
        '9.alert',
        '10.renderTable',
        '11.slotScopeTable',
        '12.tree',
        '13.publish',
    ],
    '/source/vue-cli2.x/': [
        '1.index'
    ],
    '/source/vue2.x/': [
        '1.index',
        '2.initGlobalAPI',
        '3.initMixin',
        '4.stateMixin',
        '5.eventsMixin',
        '6.lifecycleMixin',
        '7.renderMixin',
        '8.mount',
        '9.ast',
        '10.optimize',
        '11.gencode',
        '12.mount',
        '13._render',
        '14._update'
    ],
    '/source/vue-router3.x/': [
        '1.index',
        '2.origin'
    ],
}
module.exports = sidebar